---
- hosts: webserver
  become: yes
  tasks:
  - name: Install EPEL Repo
    yum:
      name: epel-release
      state: latest

  - name: Install nginx and additional
    yum:
      name:
        - net-tools
        - nano
        - vim
        - tcpdump
        - lynx
        - policycoreutils-python
        - rsyslog
      state: present

  - name: NGINX | Install NGINX package from EPEL Repo
    yum:
      name: nginx
      state: latest
    
  - name: NGINX | Create NGINX config file from template
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf

  - name: cp index
    template:
      src: index.j2
      dest: /usr/share/nginx/html/index.html
    notify: restart nginx
    
  - name: cp all.conf
    template:
      src: all.conf_webserver.j2
      dest: /etc/rsyslog.d/all.conf
    notify: restart rsyslog

  - name: cp errors.conf
    template:
      src: errors.conf_webserver.j2
      dest: /etc/rsyslog.d/errors.conf
    notify: restart rsyslog
    
  - name: cp listen.conf
    template:
      src: listen.conf_webserver.j2
      dest: /etc/rsyslog.d/listen.conf
    notify: restart rsyslog

  - name: cp rsyslog.conf
    template:
      src: rsyslog.conf_webserver.j2
      dest: /etc/rsyslog.conf
    notify: restart rsyslog  
  
  - name: restart nginx
    notify: restart nginx

  handlers:
  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes
        
  - name: restart rsyslog
    systemd:
      name: rsyslog
      state: restarted
      enabled: yes
    
  - name: reload nginx
    systemd:
      name: nginx
      state: reloaded
    
- hosts: rsyslog
  become: yes
  tasks:
  
  - name: Install EPEL Repo
    yum:
      name: epel-release
      state: latest
  
  - name:
    yum:
      name:
        - net-tools
        - nano
        - vim
        - tcpdump
        - lynx
        - policycoreutils-python
        - rsyslog
        - chrony
      state: present
      
  - name: cp rsyslog.conf
    template:
      src: rsyslog.conf_rsyslog.j2
      dest: /etc/rsyslog.d/rsyslog.conf
    notify: restart rsyslog

  - name: Allow rsyslog to listen on tcp port 514
    seport:
      ports: 514
      proto: tcp
      setype: syslogd_port_t
      state: present

  - name: Allow rsyslog to listen on udp port 514
    seport:
      ports: 514
      proto: udp
      setype: syslogd_port_t
      state: present
      
  handlers:
  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes
        
  - name: restart rsyslog
    systemd:
      name: rsyslog
      state: restarted
      enabled: yes
    
  - name: reload nginx
    systemd:
      name: nginx
      state: reloaded
