---
- hosts: webserver
  become: yes
  tasks:
  - name: Install nginx and additional
    yum:
      name:
        - nginx
        - net-tools
        - nano
        - vim
        - tcpdump
      state: present
  
  - name: NGINX | Create NGINX config file from template
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify:
    - reload nginx
    
  - name: selinux /etc/named/
    sefcontext:
      target: '/etc/named(/.*)?'
      setype: named_zone_t
      state: present
      reload: yes
    register: selinux
    
  - name: apply  file context 
    shell: |
      restorecon -Rv /etc/named
    when: selinux.changed
    
    
  - name: ensure named is running and enabled
    service: name=named state=restarted enabled=yes

    
- hosts: rsyslog
  become: yes
  tasks:
 
 
  - name: copy named.conf
    copy: src=slave-named.conf dest=/etc/named.conf owner=root group=named mode=0640
  - name: copy resolv.conf to the servers
    copy: src=servers-resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644

  - name: set /etc/named permissions
    file: path=/etc/named owner=root group=named mode=0670

  - name: selinux /etc/named/
    sefcontext:
      target: '/etc/named(/.*)?'
      setype: named_zone_t
      state: present
      reload: yes
    register: selinux
    
  - name: apply  file context 
    shell: |
      restorecon -Rv /etc/named
    when: selinux.changed
    
    
  - name: ensure named is running and enabled
    service: name=named state=restarted enabled=yes
